import os
from pathlib import Path
import sys
import re

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

    """
    Webscrape function for Washington State Legislature Website for 2016-2020 sessions 
    
    Parameters
    ----------
    webscrape_links : LIST
        List of direct link(s) to WA committee video pages.
        Can also use list generated by wa_committee_links() 
    dir_chrome_webdriver : STRING
        Local directory that has Chrome Webdriver.
    dir_save : STRING
        Local directory to save audio files

    Returns
    -------
    All audio files found on the webscrape_links, saved on local dir_save.
    
    """

service = Service("/Users/katherinechang/Google Drive/My Drive/2021/Fall 2021/CSE583/project/chromedriver")
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=service, options=options)

driver.get("https://www.tvw.org/watch/?eventID=2021021259") 

arrow01 = driver.find_element(By.ID, 'content')
arrow01.click()

#arrow02 = driver.find_element(By.CLASS_NAME, 'interior_container')
#arrow02.click()
#arrow02 = driver.find_element(By.CLASS_NAME, 'invintus-player')
#arrow02.click()
#arrow02 = driver.find_element(By.CLASS_NAME, 'inv-underlay--actions')
#arrow02.click()

url = driver.page_source
REGEX_PATTERN = r'https.*audio.*\.mp3'
lines = url.split()
meeting_regex = re.compile(REGEX_PATTERN)
mp3_files = []

for l in lines:
    hit = meeting_regex.findall(l)
    if hit:
        mp3_files.extend(hit)
        
for filename in mp3_files:
    print(filename)
    
driver.close()


audio_file_path = str(Path(os.getcwd())) #Sets to local Github directory path

sys.path.insert(1, audio_file_path) 



"""
https://invintus-client-media.s3.amazonaws.com/9375922947/bb61b863f2ace56a560d401f1deebfc17ec0201c_audio.mp3
https://invintus-client-media.s3.amazonaws.com/9375922947/071722fb938c8e0a87505936941971725631c303_audio.mp3

NOTES:
    Audio download button available until 2016. 2015 and previous years will require video links (mp4)
"""